name: flutter_demo
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_logger:  ^0.0.4+1
  # 读取与写入文件
  path_provider: ^0.4.1
  # 图片处理
  image: ^2.0.4
  cached_network_image: ^0.4.1+1
  transparent_image: ^0.1.0
  shared_preferences: ^0.4.2
  sqflite: ^0.12.2+1
  http: ^0.11.3+16
  dio: ^1.0.9
  # 弹吐司
  fluttertoast:


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - images/
    - assets/result.json

